---
# FIXME: when login user is several, it may cause some bug.
- name: get user name
  shell: who|cut -d ' ' -f 1|head -n 1
  register: whoami
  tags:
    - vimrc
    - others
    - work

- name: install basic tools
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "curl"
      - "tmux"

- name: install editors
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "vim-gtk"
  tags: editors

- name: install zsh
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "zsh"
  tags: zsh

- name: install hyper
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
      - "gdebi"
      - "python-pexpect"
      - "libgconf2-4"
      - "gnome-panel"

- name: download linux_deb_amd64 for hyper
  shell: sudo wget https://hyper-updates.now.sh/download/linux_deb_amd64

- name: install hyper with linux_deb_amd64
  expect:
    command: sudo gdebi linux_deb_amd64
    responses:
      "Do you want to install the software package\\? \\[y/N\\]" : "y"

- shell: sudo rm linux_deb_amd64

- name: make symlink of .vimrc to home directory
  file:
    src: /home/{{whoami.stdout}}/dotfiles/.vimrc
    dest: /home/{{whoami.stdout}}/.vimrc
    state: link
  tags:
    - vimrc

- name: make symlink of .vimrc.local to home directory
  file:
    src: /home/{{whoami.stdout}}/dotfiles/.vimrc.local
    dest: /home/{{whoami.stdout}}/.vimrc.local
    state: link
  tags:
    - vimrc

- name: make symlink of .zshrc to home directory
  file:
    src: /home/{{whoami.stdout}}/dotfiles/.zshrc
    dest: /home/{{whoami.stdout}}/.zshrc
    state: link
  tags:
    - zshrc

    #- name: make symlink of .hyper.js to home directory
    #  file:
    #    src: /home/{{whoami.stdout}}/dotfiles/.hyper.js
    #    dest: /home/{{whoami.stdout}}/.hyper.js
    #    state: link
    #  tags:
    #    - hyper

- name: make symlink of .tmux.conf to home directory
  file:
    src: /home/{{whoami.stdout}}/dotfiles/.tmux.conf
    dest: /home/{{whoami.stdout}}/.tmux.conf
    state: link
  tags:
    - tmux

- name: make symlink of .tmux to home directory
  file:
    src: /home/{{whoami.stdout}}/dotfiles/.tmux
    dest: /home/{{whoami.stdout}}/.tmux
    state: link
  tags:
    - tmux

- name: install other extensions
  sudo: yes
  action: apt pkg="{{item}}" state=present update_cache=no
  with_items:
    - "bluez"
  tags:
    - others
    - extensions

- name: making Work directory at home directory
  shell: mkdir /home/{{whoami.stdout}}/Work
  tags:
    - work
